[package]
name = "bf"
authors = ["Knarkzel <knarkzel@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "brainfuck to x86-64 assembly compiler and interpreter"

[dependencies]
nom = "7.0"
anyhow = "1.0"
fehler = "1.0"

[profile.dev]
overflow-checks = false